name: Build and Pre-Release

on:
  push:
    tags:
      - 'v*.*.*-pre-*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: Configure the project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
          build-dir: NIAHttpBOT
      - name: Upload the exe file
        uses: actions/upload-artifact@v4
        with:
          name: NIAHttpBOT.exe
          path: ./NIAHttpBOT/Release/NIAHttpBOT.exe
      - name: Upload the libssl-3-x64.dll
        uses: actions/upload-artifact@v4
        with:
          name: libssl-3-x64.dll
          path: ./NIAHttpBOT/Release/libssl-3-x64.dll
      - name: Upload the libcrypto-3-x64.dll\
        uses: actions/upload-artifact@v4
        with:
          name: libcrypto-3-x64.dll
          path: ./NIAHttpBOT/Release/libcrypto-3-x64.dll

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: Configure the project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
          build-dir: NIAHttpBOT
          build-args: --config Release -j 8
      - name: Upload the executable file
        uses: actions/upload-artifact@v4
        with:
          name: NIAHttpBOT
          path: ./NIAHttpBOT/NIAHttpBOT


  release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Download the exe file
        uses: actions/download-artifact@v4
        with:
          name: NIAHttpBOT.exe
      - name: Download the libssl-3-x64.dll
        uses: actions/download-artifact@v4
        with:
          name: libssl-3-x64.dll
      - name: Download the libcrypto-3-x64.dll
        uses: actions/download-artifact@v4
        with:
          name: libcrypto-3-x64.dll
      - name: Remove existing directory
        run: rm -rf ./NIAHttpBOT
      - name: Download the Linux executable file
        uses: actions/download-artifact@v4
        with:
          name: NIAHttpBOT
      - name: Create and upload release
        uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: true
          artifacts: "NIAHttpBOT.exe,libssl-3-x64.dll,libcrypto-3-x64.dll,NIAHttpBOT"
          bodyFile: "CHANGELOG-PRE.md"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}