name: Pre Build

on:
  push:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Set timezone to Asia/Shanghai
        run: tzutil /s "China Standard Time"
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: Configure the project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
          build-dir: NIAHttpBOT
          args: --config Release
      - name: Upload the exe file
        uses: actions/upload-artifact@v4
        with:
          name: NIAHttpBOT.exe
          path: ./NIAHttpBOT/Debug/NIAHttpBOT.exe
      - name: Upload the pdb file
        uses: actions/upload-artifact@v4
        with:
          name: NIAHttpBOT.pdb
          path: ./NIAHttpBOT/Debug/NIAHttpBOT.pdb
      - name: Upload the libssl-3-x64.dll
        uses: actions/upload-artifact@v4
        with:
          name: libssl-3-x64.dll
          path: ./NIAHttpBOT/Debug/libssl-3-x64.dll
      - name: Upload the libcrypto-3-x64.dll\
        uses: actions/upload-artifact@v4
        with:
          name: libcrypto-3-x64.dll
          path: ./NIAHttpBOT/Debug/libcrypto-3-x64.dll

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Set timezone to Asia/Shanghai
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: Configure the project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
          build-dir: NIAHttpBOT
      - name: Upload the executable file
        uses: actions/upload-artifact@v4
        with:
          name: NIAHttpBOT
          path: ./NIAHttpBOT/NIAHttpBOT
